### ISSUE TITLE
XKCDPASS description.

### ISSUE THREAD

**Issue by Laxman-SM** [agabert/packernetes#2]
This generate any kind of password. if possible can you please share the details about the docker image used to create password.

XKCDPASS = docker run -it --rm --detach=false agabert/rampensau:latest --count=1

if possible can you elaborate, what logic you actually implemented here  
XCODE_NAME := $(shell $(XKCDPASS) --acrostic=$(CODE_NAME_SEED))

**Comment by agabert** [comment]
Hello Laxman, the git repo for rampensau is here: https://github.com/agabert/rampensau/blob/master/docker/rampensau/Dockerfile

**Comment by agabert** [comment]
In addition to that, the logic is that we want to create a codename for the packernetes AMI that satisfies two requirements:

* needs to consist of two simple words
* must resemble a major and a minor version

example:

```
Alexanders-MacBook-Pro:~ agabert$ docker run -it --rm --detach=false agabert/rampensau:latest --count=1 --acrostic=aa
another agency
Alexanders-MacBook-Pro:~ agabert$ docker run -it --rm --detach=false agabert/rampensau:latest --count=1 --acrostic=aa
aptitude afternoon
Alexanders-MacBook-Pro:~ agabert$ docker run -it --rm --detach=false agabert/rampensau:latest --count=1 --acrostic=ab
ashamed boozy
```
For releases of the same minor and major version, use a code name that consists of the same acrostic (aa in this case).

Jumping up a minor version: use ab as acrostic, then ac, then ad, and so on.

Jumping up a major version: use ba, bb, bc, and so on.

```
Alexanders-MacBook-Pro:~ agabert$ docker run -it --rm --detach=false agabert/rampensau:latest --count=1 --acrostic=ba
botch aghast
Alexanders-MacBook-Pro:~ agabert$ docker run -it --rm --detach=false agabert/rampensau:latest --count=1 --acrostic=bb
brisket boaster
Alexanders-MacBook-Pro:~ agabert$ docker run -it --rm --detach=false agabert/rampensau:latest --count=1 --acrostic=bc
blubber chubby
```

**Comment by agabert** [comment]
This way we can use CI builds to generate always new code names for our AMI images, that will show up in the screen session when we are logging into the machine, making them recognizable fast.

And if we want to bump the version (because big things happened behind the scenes) we can increase the acrostic.

This supports 24 major versions and 24 minor versions.

More than enough, and if we run out we can always go to a more advanced versioning schema.
